In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize

8

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6,7,8])
b

array([6, 7, 8])

### numpy的创建

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.empty((2,3))

array([[-2.68156159e+154, -2.68156159e+154,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [12]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [13]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [14]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
from numpy import pi
x = np.linspace(0,2*pi,100)
f = np.sin(x)

### numpy的常用算术

In [16]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [17]:
c = a - b
c

array([20, 29, 38, 47])

In [18]:
b**2

array([0, 1, 4, 9])

In [19]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [20]:
a<35

array([ True,  True, False, False])

### numpy的矩阵乘法

In [21]:
a = np.array([[1,1],[0,1]])
a

array([[1, 1],
       [0, 1]])

In [22]:
b = np.array([[2,0],[3,4]])
b

array([[2, 0],
       [3, 4]])

In [23]:
c = a*b
c

array([[2, 0],
       [0, 4]])

In [24]:
c = a @ b
c

array([[5, 4],
       [3, 4]])

In [25]:
c = a.dot(b)
c

array([[5, 4],
       [3, 4]])

### numpy的求最大值和求和

In [26]:
a = np.random.rand(2,4)
a

array([[0.39476734, 0.64491353, 0.15485762, 0.98998897],
       [0.9343536 , 0.12817223, 0.6100673 , 0.10600755]])

In [27]:
a.sum()

3.963128138617892

In [28]:
a.max()

0.989988968925339

In [29]:
a.min()

0.106007552687722

In [30]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [32]:
b.min(axis=1)

array([0, 4, 8])

In [33]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### numpy的常用函数

In [34]:
b = np.arange(3)
b

array([0, 1, 2])

In [35]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [36]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [37]:
c = np.array([2,-1,4])
np.add(b,c)

array([2, 0, 6])

### reshape

In [38]:
x_train = np.array([[-1, 1], [-2, 0], [-1, 0], [-0.5, 0.5], [0, 0.5],[1, 3], [2, 3], [1, 1], [1, -0.5], [1, 0]])
x_train

array([[-1. ,  1. ],
       [-2. ,  0. ],
       [-1. ,  0. ],
       [-0.5,  0.5],
       [ 0. ,  0.5],
       [ 1. ,  3. ],
       [ 2. ,  3. ],
       [ 1. ,  1. ],
       [ 1. , -0.5],
       [ 1. ,  0. ]])

In [39]:
x_train.shape

(10, 2)

In [40]:
x_train = x_train.reshape(10,2,1)
x_train

array([[[-1. ],
        [ 1. ]],

       [[-2. ],
        [ 0. ]],

       [[-1. ],
        [ 0. ]],

       [[-0.5],
        [ 0.5]],

       [[ 0. ],
        [ 0.5]],

       [[ 1. ],
        [ 3. ]],

       [[ 2. ],
        [ 3. ]],

       [[ 1. ],
        [ 1. ]],

       [[ 1. ],
        [-0.5]],

       [[ 1. ],
        [ 0. ]]])

In [41]:
np.random.rand(2,1)

array([[0.49495286],
       [0.20203421]])

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
temp = np.array([1,2,3])
ans = np.sum((arr - temp)**2,axis=1) 
np.sqrt(ans)

array([ 0.        ,  5.19615242, 10.39230485])

In [43]:
a=np.random.randint(0,10,(3,3))
a

array([[4, 1, 9],
       [2, 8, 6],
       [8, 9, 7]])

In [44]:
b=np.array(a[0,:])
b

array([4, 1, 9])

In [45]:
c=a[2,:]
c

array([8, 9, 7])

In [46]:
a[0,:]=c
a

array([[8, 9, 7],
       [2, 8, 6],
       [8, 9, 7]])

In [48]:
a[2,:]=b
a

array([[8, 9, 7],
       [2, 8, 6],
       [4, 1, 9]])